### ISSUE TITLE
Support checkout webhooks

### ISSUE THREAD

**Issue by aldarund** [stripe/stripe-cli#151]
### Problem
Testing checkout webhook
checkout.session.completed
I cant even find docs what will object checkout.session.completed look like in webhook and cant test with cli and testing on real domains or tunnels is a pain

### Feature
trigger checkout.session.completed

**Comment by tomer-stripe** [comment]
Hey @aldarund, I'll talk to the team and see what we can do here.

**Comment by ThomasLandauer** [comment]
`checkout.session.completed` is the most basic webhook event, isn't it? So I'm wondering why you implemented such "exotic" events as `invoice.finalized` first...

**Comment by ob-stripe** [comment]
We just released v0.6.10 with support for triggering `checkout.session.completed` events.

**Comment by aldarund** [comment]
@ob-stripe dont seem to be working. When i trigger it im getting an error.
stripe trigger checkout.session.completed
Trigger failed: Unable to retrieve CheckoutSession ID
Unable to retrieve CheckoutSession ID

And as i see i dont need to provide any param as when i try it complains about it. Also its missing on your wiki page https://github.com/stripe/stripe-cli/wiki/trigger:-supported-events

**Comment by ob-stripe** [comment]
@aldarund The error message is misleading, this means one of the API requests failed for some reason. I'll push a fix to provide a better error, which should help us figure out why the command is failing for you.

I've also updated the wiki page, thanks!

**Comment by ob-stripe** [comment]
@aldarund Could you upgrade to version 0.6.12 and try again? I expect the command to still fail, but hopefully we should get a clearer error message.

**Comment by ThomasLandauer** [comment]
`checkout.session.completed` is missing in this list too: https://stripe.com/docs/stripe-cli#supported-events

**Comment by ThomasLandauer** [comment]
Since there's no documentation available (yet), please allow me to ask here.

I just want to test if my webhook handler is working. That's all :-) So I'm doing `stripe trigger checkout.session.completed`, right? This gives me 6 result lines in the `listen` console window:
`payment_intent.created`
`customer.created`
`payment_method.attached`
`charge.succeeded`
`payment_intent.succeeded`
`checkout.session.completed`
They are resulting in a `400` or `500` error - can I somewhere see the full response of my server?

And what's the entire workflow?
a: Create (and finish?) a payment in the browser, then request its webhook through the CLI? Or
b: Do the entire payment process (6 steps from above) through the CLI?

If (a): How do I pass the details (ID?) of the payment for which I want to trigger the webhook? Can I somehow add the `payment_intent` to the `trigger checkout.session.completed` CLI call?

Thank you!

**Comment by aldarund** [comment]
The error is following
```
    "message": "The provided key 'rk_test_ui****************************C2gi' does not have the required permissions for this endpoint on account 'acct_1EYZ0UHL36ZZY9JV'. Having the 'rak_checkout_session_write' permission would allow this request to continue.",
    "type": "invalid_request_error"
```

**Comment by joek-stripe** [comment]
> The error is following
> 
> ```
>     "message": "The provided key 'rk_test_ui****************************C2gi' does not have the required permissions for this endpoint on account 'acct_1EYZ0UHL36ZZY9JV'. Having the 'rak_checkout_session_write' permission would allow this request to continue.",
>     "type": "invalid_request_error"
> ```

To facilitate this request we actually had to extend the capabilities of the restricted API keys (rak). 

To fix this issue

1. https://dashboard.stripe.com/test/apikeys 
2. select "edit key" on your restricted API key
3. enable "write" permissions on "all checkout resources" as seen in attached screenshot

<img width="1150" alt="Screen Shot 2019-10-02 at 10 00 12 AM" src="https://user-images.githubusercontent.com/55263678/66065182-b2d8fd00-e4fb-11e9-8359-be89350a741f.png">

**Comment by joek-stripe** [comment]
> They are resulting in a `400` or `500` error - can I somewhere see the full response of my server?

yes, navigate to https://dashboard.stripe.com/test/logs


> And what's the entire workflow?
> a: Create (and finish?) a payment in the browser, then request its webhook through the CLI? Or
> b: Do the entire payment process (6 steps from above) through the CLI?
> 
> If (a): How do I pass the details (ID?) of the payment for which I want to trigger the webhook? Can I somehow add the `payment_intent` to the `trigger checkout.session.completed` CLI call?

the current functionality of this trigger is as you state in (b), however its hardcoded to a test payment token (https://stripe.com/docs/testing). If there is a more intuitive or useful behaviour that you'd prefer to see, please share

**Comment by ThomasLandauer** [comment]
> yes, navigate to https://dashboard.stripe.com/test/logs

That's not working, since I'm using it on my development machine with `--forward-to`. Is there a way to echo the server's response to the terminal window, or write it to some logfile?

My use case for the CLI is automated testing. So my preferred behavior/workflow would be:
1. Start a payment in the browser. When setting up the session with `\Stripe\Checkout\Session::create`, I'm getting the `payment_intent` which I'm storing in the database.
1. Walk through the payment process in the browser.
1. Now have Stripe CLI post the "success" notification for this specific payment to my webhook, so I can check if the script handles it correctly (and flags the payment as done in the database).

**Comment by ob-stripe** [comment]
> Is there a way to echo the server's response to the terminal window, or write it to some logfile?

Not at the moment. We're working on making the local endpoint responses visible through the dashboard, but printing in the terminal or piping to a local log file is also something we could do. We'll look into it, thanks for the suggestion!

**Comment by ThomasLandauer** [comment]
> hardcoded to a test payment token (https://stripe.com/docs/testing)

The credit card number is hardcoded, but not the payment_intent number (`pi_`...), right?

**Comment by joek-stripe** [comment]
> > hardcoded to a test payment token (https://stripe.com/docs/testing)
> 
> The credit card number is hardcoded, but not the payment_intent number (`pi_`...), right?

Yes that is fed through to the next request as can be seen here https://github.com/stripe/stripe-cli/blob/master/pkg/requests/examples.go#L179

Also if it's helpful here is the mock to flex that flow https://github.com/stripe/stripe-cli/blob/master/pkg/requests/examples_test.go#L387

**Comment by ThomasLandauer** [comment]
How can I ask for the webhook of a *specific* payment?

I'm setting up the checkout session like this:
```bash
stripe checkout sessions create success_url=http://example.com cancel_url=http://example.com payment_method_types[]=card mode=payment line_items[][amount]=100 line_items[][name]=Test line_items[][currency]=eur line_items[][quantity]=1 client_reference_id=1
```
This seems to work. Now I'd like to trigger the notification for * this* payment. But when I do `stripe trigger checkout.session.completed` I'm getting a new payment?!

**Comment by ob-stripe** [comment]
At the moment, you can't. `stripe trigger <event_type>` will always create a new API resource for the event type you want to trigger, and can't be used to affect existing API resources. (We'll probably add the ability to do this in the future, but we're not quite sure yet what exact shape the feature will take -- Stripe's API has a lot of different events and we'd like to have a somewhat generic interface.)

For triggering a `checkout.session.completed` event for an existing Checkout Session, right now you have to do one of these two things:
1. either manually confirm the session (by going to the session's URL and completing the flow)
2. or do what the CLI does under the hood and send requests to some undocumented endpoints to complete the session (which is what @joek-stripe linked to earlier). Unfortunately this is not great because these endpoints are not stable and may change without advance notice, and may also fail in non-obvious ways.

We're aware that neither of these are a great developer experience and are actively thinking of ways to improve this, but it may be some time until these efforts result in a concrete solution. Thanks for your feedback and patience!

**Comment by ThomasLandauer** [comment]
> either manually confirm the session (by going to the session's URL and completing the flow)

You mean, do what the end-user does in the browser after being redirected to https://checkout.stripe.com/pay/... ?

In general: What I'm looking for is a way to get my tests running on my development machine (that doesn't have a public IP).

**Comment by prateeknarayan** [comment]
I have implemented Stripe Checkout Process and it's working as expected, but the problem is why checkout.session.completed isn't working? 

Can anyone kindly help me out because it's very frustrating now... There is no extra information in Logs panel of Stripe panel, they just show only status of the request i.e either success or failed...

**Comment by ob-stripe** [comment]
@prateeknarayan GitHub issues should be limited to bugs or feature requests for the CLI, they are not a general support channel. You can reach out to Stripe's support at https://support.stripe.com/email.
