### ISSUE TITLE
stripe cli login stuck on "Waiting for confirmation"

### ISSUE THREAD

**Issue by davefinarb** [stripe/stripe-cli#209]
### Issue
stripe login --api-key pk_test_**** 
it then shows
Your pairing code is: some-codes
This pairing code verifies your authentication with Stripe.
Press Enter to open the browser (^C to quit)
⣯ Waiting for confirmation...
Then it sticks in it and after some mins it shows 
exceeded max attempts and quits

### Expected Behavior
Probably opens a browser. Not sure.

### Environment
Ubuntu 19 Linux

**Comment by ob-stripe** [comment]
Hi @davefinarb, thanks for the report. Indeed, the `stripe login` command should open your browser and take you to a confirmation page to grant access to your Stripe account to the CLI.

Could you confirm the following?

- Are you running the `stripe login` command from a graphical environment?
- What happens if you run `xdg-open https://stripe.com` from a terminal?

**Comment by ob-stripe** [comment]
Weird! Thanks for closing the loop anyway.

**Comment by chrisjsimpson** [comment]
Same here, running 
`xdg-open https://stripe.com`

Resets whatever it needed to. 

Before this, firefox opens, but it's just 'waiting' (no url in url bar)

**Comment by chrisjsimpson** [comment]
Hi @ob-stripe

Made a quick video showing this behaviour https://www.youtube.com/watch?v=jrgS6uiPm1M&feature=youtu.be

```stripe version 1.5.1```

**Comment by garyo** [comment]
Is there a way to print the browser URL instead, on systems that don't have a browser installed (I'm on WSL1 on Windows)? I know it's going to create a restricted key with certain permissions, so I'd like to use this method rather than creating my own restricted key that might have the wrong permissions.

**Comment by jonpastore** [comment]
I'm having the same problem, running pop_os. Tried `xdg-open https://stripe.com` and got the error that `DISPLAY was not set`, I exported the DISPLAY=:0 and it still fails. having the tool display the path so we can at least copy and paste it into a browser would be very handy.

**Comment by ntm1627** [comment]
Any same solution for windows, running the command from Windows PowerShell is ending with the same error message.
Thanks

**Comment by danjdewhurst** [comment]
> Any same solution for windows, running the command from Windows PowerShell is ending with the same error message. Thanks

I started having a similar issue, using command prompt instead of powershell seemed to fix it.

**Comment by cp99says** [comment]
Too late to address the issue, but I was having the same issue.

I tried running the stripe-cli using interactive mode, and provided the secret key, it worked.

```
stripe login --interactive
<provide your secret key>
```

and you are good to go!!

Too late to address the issue, but this is how I fixed it!
