### ISSUE TITLE
trigger payment_intent.created with listen --forward-to local sends 3 POST requests

### ISSUE THREAD

**Issue by jakemaas1** [stripe/stripe-cli#212]
### Issue
Apologies if this is a me issue, and not a bug, but I am having the following problem: 

I am testing a rails endpoint set up to accept the `payment_intent.succeeded` webhook, and when triggering the event I am seeing 3  subsequent POST requests to my local server. 

My webook is set up from the dashboard to only notify on payment_intent success/failure. 

### Expected Behavior
I expect there to be 1 POST request (for the payment intent success) rather than 3. 

### Steps to reproduce
- I have my local server running and am listening with `stripe listen --forward-to <local server>`. 
- When I trigger a `payment_intent.succeeded`, I invariably see 3 separate POST requests to my server. 

### Traceback
From cli trigger window: 
 ```
> stripe trigger payment_intent.succeeded
Trigger succeeded! Check dashboard for event details.
```

From `stripe listen` window: 

``` 
stripe listen --forward-to localhost:3000/services/stripe/payment_intents
> Ready! Your webhook signing secret is <SECRET> (^C to quit)
2019-10-01 13:37:26  Received: payment_intent.created [evt_1FOs6EEeqVASFOA53jddw7Q8]
2019-10-01 13:37:26  Received: charge.succeeded [evt_1FOs6EEeqVASFOA56kApBNZN]
2019-10-01 13:37:26  Received: payment_intent.succeeded [evt_1FOs6FEeqVASFOA5veXZwo3O]
2019-10-01 13:37:26            [200] POST http://localhost:3000/services/stripe/payment_intents
2019-10-01 13:37:26            [200] POST http://localhost:3000/services/stripe/payment_intents
2019-10-01 13:37:26            [200] POST http://localhost:3000/services/stripe/payment_intents
```

From my local server window:
```
Started POST "/services/stripe/payment_intents" for ::1 at 2019-10-01 13:37:26 -0700
Processing by....
X 3
```

It seems like the trigger is not recognizing the webhook settings in the UI and sending all downstream events anyway? 

### Environment
macOS

**Comment by ob-stripe** [comment]
Hi @jakemaas1. AFAICT this is expected behavior. The CLI triggers specific events by sending regular API requests on your behalf. Some events cannot be triggered by a single API request and cause side-effects: for example, in order to trigger a `payment_intent.succeeded` event, the CLI must first send a payment intent creation request (resulting in a `payment_intent.created` event), then confirm it (resulting in both a `charge.succeeded` and a `payment_intent.succeeded` event).

If you only want to receive a specific event type (or a few specific event types) when forwarding events to your local integration using `stripe listen`, you can do so using the `--events` (or `-e`) flag, e.g.:

```
$ stripe listen --forward-to localhost:3000/services/stripe/payment_intents --events payment_intent.succeeded
```

When invoked like this, the CLI will still receive all 3 events from Stripe, but it will only forward the `payment_intent.succeeded` event to your integration.

Hope that clarifies things! Closing as this doesn't appear to be a bug, but feel free to reply (especially if you have suggestions on how to make this behavior clearer!).
