### ISSUE TITLE
`--api-version` not working

### ISSUE THREAD

**Issue by ThomasLandauer** [stripe/stripe-cli#213]
`stripe listen --api-version 2019-09-09` results in:
> unknown flag: --api-version

The same goes for `stripe trigger checkout.session.completed --api-version 2019-09-09`

Second issue:  
It looks like Stripe CLI is defaulting to the 2019-03-14 API version, not to my currently used API version.

I have:
> stripe version 0.6.12 (beta)

**Comment by ob-stripe** [comment]
Unfortunately, due to technical constraints on the backend, the `listen` command can only support two different API versions:
- by default, events will be formatted according to your account's default API version (which you can view at https://dashboard.stripe.com/developers)
- alternatively, you can request that events be formatted with the latest API version by using the `--latest` (or `-l`) flag

Relatedly, the `trigger` command also doesn't support specific API versions. The events are formatted by Stripe's backend servers:
- if you're receiving events via the `stripe listen` command, then events will be formatted as explained above
- if you're receiving events via a regular webhook endpoint, then events will be formatted according to the endpoint's API version

> Second issue:
> It looks like Stripe CLI is defaulting to the 2019-03-14 API version, not to my currently used API version.

For the trigger command, yes, API requests that are sent by the CLI in order to trigger the requested event do use that API version. But that doesn't control the API version that will be used to format the event object you receive on your endpoint.

**Comment by ThomasLandauer** [comment]
I think what you're saying conflicts with the docs at https://stripe.com/docs/stripe-cli#api-requests - doesn't it?

**Comment by ob-stripe** [comment]
No. When using API requests commands (e.g. `stripe charges create`, `stripe customers update`, etc.), you can specify any API version. This controls which parameters are accepted in the request, and how the API response is formatted.

However, it doesn't control which API version will be used to format the resulting event (if any). This is briefly mentioned here: https://stripe.com/docs/api/versioning

> _Note that events generated by API requests will always be structured according to your account API version._

(Though this isn't 100% correct -- when setting up a webhook endpoint, or when using `stripe listen` with the `--latest` flag, you can request that events be formatted with the latest API version instead of your account's default version.)

This is how events work in Stripe's API and is not specific to the CLI.

Can you clarify your usecase? In nearly all cases, you want events to be formatted with your account's default API version (or the latest, when you're preparing to upgrade your account's default API version to the latest).

**Comment by ThomasLandauer** [comment]
No real use case, I just noticed some usage of the 2019-03-14 API version in my dashboard (test mode) after starting to use the CLI, and was wondering if I'm doing something wrong. My default is 2019-09-09.

Anyway, I guess it's not too important, so if you think it's not a bug, and the docs are correct, you can close this ;-)

**Comment by stephencelis** [comment]
FWIW, this is an issue for us, as well. Our use case was we were prepared to update to a more recent version of the Stripe API (but not latest).

**Comment by vcombey** [comment]
this is an issue for us too. After a stripe account migration, our account default version is after the version we are using. So I can't test webhooks locally..

**Comment by ryanseys** [comment]
Just adding another +1 here that this is an issue for us too. Would be nice to be able to fetch events with a given API version, either through the Stripe CLI or through Events.List API call (which also currently suffers from this same limitation)

**Comment by kion** [comment]
+1. It's a real issue that API version can't be specified for the `stripe listen` command.

**Comment by arnav13081994** [comment]
+1 This would be very useful to test upgrading to a more recent stripe version which is not the `latest`.

**Comment by RobinSoenen** [comment]
+1 Also blocking for local development

**Comment by cwqt** [comment]
this wouldn't be so bad if not for the inability to incrementally update the accounts default API version, forcing users to go from some version all the way to latest seriously sucks

**Comment by Meleeman01** [comment]
had this same problem with a recent 2022-version i need to use to test with. and for some reason it defaults to the 4 year old version on the cli.

**Comment by lenardchristopher** [comment]
Also blocking. :)

**Comment by Sirozha1337** [comment]
Same problem here. I have a project running on API version of 2020, I try to test it with sandbox, but I'm on a new account with latest version and of course it doesn't work. I don't want to use the sandbox from production account because it's a security risk and I don't want to upgrade my API version, because it might introduce bugs. 

Is there any hope you might reconsider changing this behaviour?

**Comment by mmatchenko** [comment]
this is so annoying

**Comment by lenichols** [comment]
Still no fix for this? Ugghhh

**Comment by ahomaidat** [comment]
no fix yet? quite amusing!

**Comment by JaidonLalor** [comment]
Looking for this feature too...

**Comment by farnell** [comment]
this is an issue for me also, trying to local listen to a beta API webhook and I can't specify the beta API version so I can't test this???

**Comment by dimitris-katsigiorgis** [comment]
This bug needs to be reopened since its a major issue. Or at least give us a workaround.

**Comment by MrJuliuss** [comment]
Hi, same issue here. No news about this since 2019 ?

**Comment by luc4salmeida** [comment]
Hi, same issue here, I can't specify what API Version the listen should use to forward the events.

**Comment by bpiroman** [comment]
Follow these steps in the link below

https://docs.stripe.com/upgrades#how-can-i-upgrade-my-api

activate workbench, turn off live mode, then upgrade API version

**Comment by HackerQED** [comment]
+1, I cannot test my webhook locally
