### ISSUE TITLE
Simulating Connect Platform events

### ISSUE THREAD

**Issue by kypalmer** [stripe/stripe-cli#293]
### Problem
Test features in a connect platform app that rely on Connect Webhooks. 

### Feature
An ability to simulate Connect Webhooks for test-mode connected accounts. Ideally, it would be possible to specify the account to use, so that the local dev app can keep the test-mode account id stored. 

Specifying the hierarcy of the request could also be useful. For example, when triggering an invoice, saying that it's for a specific subscription (again that way it can be saved in app).

### Examples
`stripe trigger invoice.payment-succeeded --account=<testmode_connected_acct> --subscription=<testmode_subscription_from_connected_account>`

**Comment by ob-stripe** [comment]
Triggering events on a connected account is definitely doable -- we'll look into adding support for that.

Unfortunately, being able to pass custom data into triggered events (e.g. passing an existing subscription object ID when triggering an `invoice.payment_succeeded` event)  is a lot more complex, at least with the way it's currently implemented. Since several users have requested something to that effect, I've opened a separate issue to explain the current state and centralize discussion: #295.

**Comment by ob-stripe** [comment]
We just released v1.3.1 which adds support for triggering events on connected accounts. You can use the `--stripe-account` flag with the `trigger` and `fixtures` commands to execute the requests on a connected account.
