### ISSUE TITLE
Stripe install GPG error "gpg: keyserver receive failed: Cannot assign requested address"

### ISSUE THREAD

**Issue by Freezystem** [stripe/stripe-cli#294]
### Issue
adding a GPG key fail when running `apt-key` command  into CI.

### Expected Behavior
This command  should install GPG key without failing to allow the installation of stripe-cli.

### Steps to reproduce
run `sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys 379CE192D401AB61`

### Traceback
```
Executing: /tmp/apt-key-gpghome.C8NYbEHllY/gpg.1.sh --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys 379CE192D401AB61
gpg: keyserver receive failed: Cannot assign requested address
```
 
### Environment
CircleCI Debian base docker image: [circleci/clojure:openjdk-8-lein-2.9.1-node](https://hub.docker.com/layers/circleci/clojure/openjdk-8-lein-2.9.1-node/images/sha256-6e6e5edeac3909b3f0280880721763a19d223296be2361f417ecef21529b6cc6)

**Comment by Freezystem** [comment]
Note: removing port 80 in hkp address (added since [this bug report](https://github.com/stripe/stripe-cli/issues/231)) solve the issue: `hkp://pool.sks-keyservers.net`

**Comment by Freezystem** [comment]
It seems that all first calls from a new build machine are failing, making the CI job to fail. 
Running the job another time make it work.
I wonder if it's the CI or the GPG key server fault. 🤔

**Comment by Freezystem** [comment]
aaaaaand no it's randomly failing/succeeding. Sorry....! 😄

**Comment by ob-stripe** [comment]
Hey @Freezystem, thanks for the report.

I can't be 100% sure, but I suspect the issue is on CircleCI's side. I found some threads reporting similar issues, e.g. https://discuss.circleci.com/t/cannot-reach-p80-pool-sks-keyservers-net-from-remote-docker-containers/15226, https://discuss.circleci.com/t/builds-failing-to-contact-keyserver/8740/4 or https://discuss.circleci.com/t/failure-to-contact-a-key-server/25808.

That last thread offers a decent workaround: put the GPG public key in an environment variable so you don't have to import it from the key server.

Alternatively, if Circle CI lets you use Docker, you could use the CLI's Docker image rather than installing the CLI as a system package.

**Comment by Freezystem** [comment]
I used to rely on the stripe-cli docker container but I needed to be able to pass it env vars. Unfortunately tiers docker container are declared before env var can be used in CircleCI yaml script. So I finally had to rely on the stripe-cli apt package.
I'm currently using `sudo apt-get install stripe=1.0.1 -y --allow-unauthenticated` as an unsafe workaround for the moment and will try to download the key like they do in the discuss thread.
Thanks for your help.
