### ISSUE TITLE
Typo: "Unrecogized..." when requesting `stripe get <plan_id>`

### ISSUE THREAD

**Issue by omarzina** [stripe/stripe-cli#337]
### Issue
Trying to get a plan by id returns `Unrecogized object id: <plan_id>`.

### Expected Behavior
It should return `Unrecognized...`.
Besides, the plan actually exists, as I can successfully retrieve it using `stripe plans retrieve <plan_id>` but I don't know if this is an expected behavior.

### Steps to reproduce
It seems weird that it only happens with the specific plan that I'm trying. If I enter any string the response is different. I don't know if it's secure to disclose plan id here. Please advise and I'll do.

### Environment
macOS Mojave, Homebrew

### Source affected
[base.go:311](https://github.com/stripe/stripe-cli/blob/7bdcb357c548806e5bc43f286893b1063c87b3a2/pkg/requests/base.go#L311)

**Comment by ob-stripe** [comment]
`stripe get` relies on ID prefixes to know which endpoint to use to retrieve the resource. E.g. if you type `stripe get cus_123`, the CLI can infer that you're trying to retrieve a custom object from the `cus_` prefix.

Unfortunately, that strategy cannot work for objects with user-settable IDs that don't have a prefix, like plans. Since there's more than one object type where this is possible (plans, products, SKUs, maybe a couple others), it's not possible to guess the type. So for those object types, you have to explicitly specify the type by using e.g. `stripe plans retrieve my_awesome_plan`.

We should improve the error message though, I think you got confused because `Unrecogized object id` sounds like the object ID is invalid, when in fact it means the CLI could not infer the object type from the ID.

> I don't know if it's secure to disclose plan id here.

Stripe object IDs are not particularly sensitive, since they're useless without your secret API key. That said in this case you don't need to share the plan ID, it's pretty clear what happened.

**Comment by omarzina** [comment]
Got it! Thank you very much Olivier for the explanation.

**Comment by ob-stripe** [comment]
The typo was fixed in #350.
