### ISSUE TITLE
windows Stripe cli token is misleading

### ISSUE THREAD

**Issue by rajeshnarayanan2019** [stripe/stripe-cli#356]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue
windows Stripe cli token is printing like ←[1mwhsec_zGikAg19N5FOHXai7uOuzD8HHErIByOw←[0m 

### Expected Behavior
it should generate token like this whsec_zGikAg19N5FOHXai7uOuzD8HHErIByOw

### Steps to reproduce
start stripe cli in window command prompt

### Traceback
Ready! Your webhook signing secret is ←[1mwhsec_zGikAg19N5FOHXai7uOuzD8HHErIByOw←[0m (^C to quit)

### Environment
Windows

**Comment by ob-stripe** [comment]
Hi @rajeshnarayanan2019. This is due to older Windows versions not supporting ANSI color codes. Recent Windows 10 builds do support ANSI color codes and will display the signing secret (and other colored output) correctly.

Unfortunately there is no reliable way of detecting whether the console supports ANSI color codes or not, so this is not something that can be fixed in the Stripe CLI itself.

If you're running an older Windows version, the best thing to do is to disable color output entirely.  You can use the `--color off` to do this on a one off basis, or you can call `stripe config --set color off` to disable colors permanently.
