### ISSUE TITLE
AVG AntiVirus flags the CLI as suspicious

### ISSUE THREAD

**Issue by tomer-stripe** [stripe/stripe-cli#43]
Reported by @homemadePopcorn in #37:

> stripe.exe was labelled as a suspicious file by my anti-virus software. I can add an exception to that file on my firewall but just thought I would write the issue down.

Is there something we can do to make Windows happier with that behavior? We didn't have issues with this when we were doing Windows testing locally, wonder if there's something specific it's flagging.

**Comment by ob-stripe** [comment]
@homemadePopcorn Can you tell a little more about your environment? I.e. Windows version, antivirus name and version, or anything else that could help in reproducing the issue.

**Comment by homemadePopcorn** [comment]
Sure, I'm using AVG Anti-virus software v19.6.3098.  Windows 10 pro v1903.

**Comment by ob-stripe** [comment]
Thanks!

I just uploaded `stripe.exe` from the 0.2.2 release to virustotal.com, here are the results: https://www.virustotal.com/gui/file/b9bb89ba261974e9bfe2146f76fffe98d8e3681eb249e59835b132c9b5f6ec81/detection

AVG reports no issues there, but you might have different settings on your computer.

My guess is that AVG is being overly paranoid because this is a new executable it's never seen before. Hopefully once enough people start using the CLI it will get whitelisted. If this becomes a recurring issue we can also see about directly reaching out antivirus software providers.

**Comment by ob-stripe** [comment]
Oh, I wonder if this is because we try to run `uname -a` to compute the extended user agent. We can probably exclude that entirely on Windows since the chances of `uname` existing on Windows are very slim.

**Comment by tomer-stripe** [comment]
Going to close this since we think we might've addressed the underlying issue! We can re-open if it surfaces again.
