### ISSUE TITLE
Make it easier to obtain the webhook signing secret by implementing `stripe listen --print-secret`

### ISSUE THREAD

**Issue by bwang-stripe** [stripe/stripe-cli#475]
### Problem
Users often need to access their [webhook signing secret(s)](https://stripe.com/docs/webhooks/signatures) from within their code. (See #472).  

Right now, this secret appears in the output of `stripe listen`, which means it requires extra work to parse. Users have to either copy it manually from the output, or use shell commands to parse it. It would be nice if users could easily get the signing secret via the command-line, and then use it as they wish (eg: by setting a local environment variable). 

### Feature
Add a `--print-secret` flag to `stripe listen` that simply prints out the current webhook signing secret and then exits immediately.

The webhook signing secret shouldn't change between calls, so `stripe listen` and `stripe listen --print-secret` can be called in any order. 

### Examples
```
stripe listen --print-secret
> whsec_abcdef
```

```
STRIPE_WEBHOOK_SECRET=$(stripe listen --print-secret)
> whsec_mysecret

<execute something that uses the STRIPE_WEBHOOK_SECRET environment variable>

stripe listen 
> Ready! Your webhook signing secret is whsec_mysecret (^C to quit)
```

```
# In Terminal A:
stripe listen 
> Ready! Your webhook signing secret is whsec_123 (^C to quit)

# Then, in Terminal B: 
stripe listen --print-secret
> whsec_123
```

**Comment by guanzo** [comment]
> and then exits immediately

I don't understand, the stripe cli process dies after printing the secret? So would I have to do something like 

```sh
STRIPE_WEBHOOK_SECRET=$(stripe listen --print-secret) # start stripe cli to print secret, then the process dies.
<execute something that uses the STRIPE_WEBHOOK_SECRET environment variable>

stripe listen # actually start stripe cli
```

**Comment by bwang-stripe** [comment]
Yep - that's correct! I'll update the original post to make that a bit clearer. 

And to further clarify, the webhook signing secret should not change between calls, so any ordering in time of `stripe listen` and `stripe listen --print-secret` should work.

**Comment by polybuildr** [comment]
Hello! :wave: I was wondering if you're interested in external contributions for this issue?

As far as I can tell, the control flow currently looks like this:
- In listen.go, `runListenCmd` calls `proxy.New()` and then `proxy.Run()` ([source](https://github.com/stripe/stripe-cli/blob/a023543c63cd2719ae3d980ca2173934653773fc/pkg/cmd/listen.go#L154-L167)).
- Wrapped in some retry logic, `proxy.Run()` creates a session and then creates a new websocket client ([source](https://github.com/stripe/stripe-cli/blob/a023543c63cd2719ae3d980ca2173934653773fc/pkg/proxy/proxy.go#L119-L135)).
- Then, in a goroutine, it waits to receive from the channel returned by `proxy.webSocketClient.Connected()` and only then it prints the `session.Secret` because this is part of the "Ready!" message ([source](https://github.com/stripe/stripe-cli/blob/a023543c63cd2719ae3d980ca2173934653773fc/pkg/proxy/proxy.go#L137-L141)).

Another example of retrieving the the secret is in samples.go ([source](https://github.com/stripe/stripe-cli/blob/a023543c63cd2719ae3d980ca2173934653773fc/pkg/samples/samples.go#L298-L305)) where it uses the `stripeauth.Client` to authorize and then puts the secret into the dotenv config.

I'm probably still missing something, but it looks like this is doable by doing something like: editing the cobra flags in listen.go to add `--print-secret`, then creating a Proxy, only using `proxy.createSession()` and then printing out the `session.Secret`.

Happy to give it a shot if that works for you (and if someone isn't already working on this)! :)

**Comment by polybuildr** [comment]
I've opened a pull request (#478) using a similar approach to the one I mentioned above. However, please do let me know if this isn't meant for an external contributor or someone is already working on it! :)

**Comment by bwang-stripe** [comment]
Hi @polybuildr!

That's great - thank you! We're happy to take external contributions on this issue, and thanks for being so proactive - I'll take a look at the PR today.

**Comment by bwang-stripe** [comment]
Thanks to @polybuildr this feature is now live in v1.4.5!
https://github.com/stripe/stripe-cli/releases/tag/v1.4.5
