### ISSUE TITLE
What is the difference between "Set up future payments" and "Save a card during payment" ?

### ISSUE THREAD

**Issue by Annakan** [stripe/stripe-cli#517]
### Feedback

Sorry if this is not really a "cli" question (should I post this on stack overflow instead ?) but the strip doc can be a bit confusing at times, at least for me.

The page https://stripe.com/docs/payments/save-and-reuse use the `Checkout API`
The page https://stripe.com/docs/payments/save-during-payment use the ` Payment Intents API` 

To seemingly achieve the same purpose ...

What is the difference ? 
Are they both compatible  ? 
Is  the `Payment Intents API` a subset of the `Checkout API` ?

The only difference seems to be that in the first case (Checkout) no amount is required upfront, and in the second the payment_method is charged right away on top of it being saved. But why two APIs ? 

My need is to charge a customer multiple time for a fractioned payment (part at order time,  part on delivery).

Thanks a lot for you help.

**Comment by brendanm-stripe** [comment]
HI @Annakan -- you're right that this is not really a CLI question, but neither would it do well on Stack Overflow either as it's a bit broad. In future I'd suggest asking a question like this in our #stripe IRC channel on Freenode.

This really boils own to one clear distinction: are you collecting a payment right now, or not? In other words, do you only want to save card details to use later, or do you want to collect a payment *and* save the card for later?

This distinction is precisely why the [Setup Intents](https://stripe.com/docs/payments/setup-intents) API was created, to collect card details _without_ a payment. Contrast with Payment Intents which are designed for collecting payment, and can _optionally_ be used to save the card details for later during that payment (a.k.a [setup future usage](https://stripe.com/docs/api/payment_intents/create#create_payment_intent-setup_future_usage)).

You can actually use Checkout in both cases:

- Checkout for [collecting a payment](https://stripe.com/docs/payments/accept-a-payment#add-checkout-button) can save the card by setting `payment_intent_data[setup_future_usage]=off_session` (or `on_session` -- [docs](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-payment_intent_data-setup_future_usage))
- Checkout for [setting up a saved card for later](https://stripe.com/docs/payments/save-and-reuse#create-checkout-session) is done by creating a session with `mode=setup` ([docs](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-mode))

Under the hood, Checkout manages using the Setup Intents or Payment Intents API for you based on the `mode` you've used. In that sense Checkout depends on both of these, but none is strictly a subset of the others.

I hope that clarifies things for you! Happy to answer any further questions you might have, but will otherwise close this issue.

**Comment by Annakan** [comment]
Thanks a lot it does clarify and confirm what I understood.

Sorry I have been polluting the issues here.

I was considering writing a kind of "Stripe beginner / first time contact with stripe documentation as a developer  post mortem" explaining the things that confused me or felt really unclear when exploring your documentation but have no idea where to post or send it. 
The goal is not to nag but to express things that people who know Stripe intimately might no see any more.

For instances:

* The word API is used in the docs for nearly everything from a single REST endpoint to any collection of them. Using API for a logical organisations of Endpoints for a purpose and Endpoint for the individual endpoints would clarify things I think;
 
* There is no (or I did not found any ) 360° view of the APIs explaining quickly the common blocks and their uses).
I now understand that there is two main "framework APIs" :  Checkout and Payment that are entry points and themselves use the SetupIntent, Card, Product, Price, Customer, etc API. Why is there two (not counting the deprecated ones), when to use which one, is one "the next generation", does the customer experience differ greatly, is there something possible with one, impossible with the other ... all this is still a mystery ;)

Don't know if that would be useful though.

**Comment by brendanm-stripe** [comment]
That's OK, we appreciate the feedback and aim to make things easier on developer like yourself learning to integrate with the Stripe API. 

You're always welcome to share feedback through support@stripe.com or you can also join the API discussion mailing list: https://groups.google.com/a/lists.stripe.com/g/api-discuss

We usually refer to the collection of endpoints related to any given object as that objects API (though we may refer to an endpoint as "API" in some contexts), and collectively these form the Stripe API and we publish the API Reference [here](https://stripe.com/docs/api). Discussion of the _purpose_ of any given API (collection of endpoints) lives in the docs, such as for [Payment Intents](https://stripe.com/docs/payments/payment-intents), [Setup Intents](https://stripe.com/docs/payments/setup-intents), [Payment Methods](https://stripe.com/docs/payments/payment-methods), and [older APIs](https://stripe.com/docs/payments/legacy-apis).

Checkout vs custom payment flow are really integration patterns or choices, where [Checkout](https://stripe.com/docs/payments/checkout) is a hosted solution Stripe offers as an _option_ when you don't need or want to build a custom flow with [Stripe.js & Elements](https://stripe.com/docs/stripe-js). For example in our "Accept a Payment" [guide](https://stripe.com/docs/payments/accept-a-payment) (or the [integration builder](https://stripe.com/docs/checkout/integration-builder)) we present you a choice to see how to integrate with buttons at the top for "prebuilt Checkout" vs "custom payment flow". Both Checkout and Elements are current & recommended options.

One of the challenges with discussing _how_ to integrate is that it's highly dependent on individual business needs.
