### ISSUE TITLE
Missing support for GET /v1/accounts/:account_id

### ISSUE THREAD

**Issue by richardm-stripe** [stripe/stripe-cli#553]
### Issue
`stripe accounts retrieve` corresponds to `GET /v1/account`, but the Stripe API has a different, slightly distinct endpoint `GET /v1/accounts/{account_id}` which also plausibly should be called `stripe accounts retrieve`. Right now there is no command that allows you to trigger that request.

**Comment by ritikbhatia** [comment]
Hi @richardm-stripe 
I happened to stumble upon this issue. Do you think that to call the `GET /v1/accounts/{account_id}`, we can extend the `stripe accounts retrieve command` by adding a flag like `--account_id`?

**Comment by suz-stripe** [comment]
👋   bringing you an update on this – there are some complications around our API spec which will warrant a discussion about a possible override for this command. For now, the workaround is to use the `stripe-account` flag and to override the default CLI restricted key with your secret key (the cli rk does not currently have full read privileges for platform accounts):

`stripe accounts retrieve --stripe-account=acct_123 --api-key=sk_test_456`

We've updated our docs accordingly with this workaround for the time being as well.

Thanks for your patience!

**Comment by frankie567** [comment]
Hey 👋 Sorry to dig out this but, as of May 2023, the workaround mentioned above is still necessary to retrieve a single account. Not a big deal, but the problem is that the [API docs](https://docs.stripe.com/api/accounts/retrieve?lang=cli) are still showing the "common" way, which is not working:

<img width="678" alt="Capture d’écran 2024-05-13 à 08 49 49" src="https://github.com/stripe/stripe-cli/assets/1144727/0d4d3434-965c-46ac-9b43-2dba70414f00">

```
`stripe accounts retrieve` requires exactly 0 positional arguments. See `stripe accounts retrieve --help` for supported flags and usage
```

It would be nice if the docs were showing the right command 🙂
