### ISSUE TITLE
Unable to register webhook endpoint in stripe-cli

### ISSUE THREAD

**Issue by rohit-githubAccount** [stripe/stripe-cli#671]
When I run the command

`sudo docker run --rm -it --net=bridge stripe/stripe-cli listen --forward-to http://localhost:3000/xxxxxxx --api-key API_KEY
`

On receiving event I am getting
` [ERROR] Failed to POST: Post "http://localhost:3000/xxxxxxx": dial tcp 127.0.0.1:3000: connect: connection refused
`

I am running docker on KDE Neon OS

**Comment by pepin-stripe** [comment]
Hi @rohit-githubAccount,

you can use `http://host.docker.internal:3000/xxxxxxx` instead of localhost. This is a special DNS which will resolve to the internal IP address of the container host. 

Since you are on Linux, you need to pass the `--add-host host.docker.internal:host-gateway` flag as well.

Documentation here: https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds

---
Alternatively, since you are on Linux you should be able to pass the `--network="host"`, which will not isolate the container's network stack from its host.

Documentation here: https://docs.docker.com/network/host/

Hope this helps!

**Comment by rohit-githubAccount** [comment]
Thank you for your assistance. It works.

**Comment by pepin-stripe** [comment]
Glad I could help!
