### ISSUE TITLE
Cannot Test identity.verification_session.verified event locally

### ISSUE THREAD

**Issue by shivaji118** [stripe/stripe-cli#704]
### Problem
I want to test the **identity.verification_session.verified** event in my local machine. But this event is not supported by stripe CLI.

### Feature
Can you add this event to the Stipe CLI trigger List?

### Examples
_Any example interaction you expect_

**Comment by vcheung-stripe** [comment]
Hi @shivaji118, it's currently not possible to run `stripe trigger identity.verification_session.verified` because this particular event requires user interaction to trigger, which is not supported today in the CLI. (In fact, I think all of the `identity.verification_session` events are like this.) This may be possible in the future, but I can't say for certain when it will be available.

The work around here would be to do `stripe identity verification_sessions create -d type=document` (or whatever args you want), then visit the url in the response, and then choose testmode option to submit with a verified status. This will result in the `identity.verification_session.verified` webhook being sent.

Is this work around suitable for your use case? Please let me know!

cc @dodgejoel-stripe

**Comment by shivaji118** [comment]
Thank you for your advice. It worked.
