### ISSUE TITLE
trigger doesn't `-add` new params as expected (payment_intent.succeeded event, `id` param)

### ISSUE THREAD

**Issue by peaceful-james** [stripe/stripe-cli#753]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue
I was trying to use Stripe CLI v 1.7.3 to trigger a `payment_intent.succeeded` event with custom `id`.

Here is my command:

```
stripe trigger payment_intent.succeeded --add payment_intent:id=pi_xxxxxxxxxxxxxxxxxxx
```

### Expected Behavior

Event is triggered and new param `id` is added to the json, as per docs (https://stripe.com/docs/cli/trigger#trigger-add)

### Steps to reproduce

run the command I wrote above

### Traceback

```
Running fixture for: payment_intent
Trigger failed: Request failed, status=400, body={
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameter: id",
    "param": "id",
    "type": "invalid_request_error"
  }
}
```

### Environment
Linux

**Comment by pepin-stripe** [comment]
Hello @peaceful-james and thanks for using the CLI!

The `stripe trigger` function creates objects with the Stripe API in order to be able to trigger related events, so running `stripe trigger payment_intent.succeeded` actually creates a `payment_intent` object to allow a `payment_intent.succeeded` event to actually be triggered.

The Stripe API doesn't allow setting an explicit id when creating resources, and this is the error you are seeing - the `id` is indeed a `parameter_unknown` when trying to create a resource. You will get the same error trying to create a payment_intent with cURL and passing an id:

```
$ curl https://api.stripe.com/v1/payment_intents -d id= pi_xxxxxxxxxxxxxxxxxxx -u <redacted>
{
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameter: id",
    "param": "id",
    "type": "invalid_request_error"
  }
}
```

So it's not possible to use the `--add` option with a parameter that is invalid with the Stripe API. 

I see how being able to trigger webhook events with a specific object id can be useful, especially for automated testing. We do not have a great solution for that quiet yet, but are currently investing in offer an improved experience for testing Stripe integration.

Hope this helps! Please feel free to re-open the task if you have additional questions!

Cheers
Jon

**Comment by carlos-menezes** [comment]
Hey. Is there any news on this matter? I'd like to trigger `payment_intent.succeeded` for a specific `id` but it's still not possible as of 2024.

**Comment by tosulc** [comment]
Would still be helpful to have. Any plans on adding it?
