### ISSUE TITLE
Stripe webhook testing not working with virtualhost

### ISSUE THREAD

**Issue by darkylmnx** [stripe/stripe-cli#784]
### Issue
I'm trying to test my webhooks with the CLI.
My local app is on a virtualhost like `app.localhost` and not just on `localhost`.

So logically, I tried the regular listen command on my endpoint:
`stripe listen --forward-to app.localhost/api/v1/webhooks/payments/subscriptions/charge`

And I got the following error:
`[ERROR] Failed to POST: Post "http://app.localhost/api/v1/webhooks/payments/subscriptions/charge": dial tcp: lookup api.teachizy.localhost: no such host`

### Expected Behavior
I was expecting the webhook to work as the docs says it should with localhost.

### Steps to reproduce
1. create a Virtual Host on your machine
2. run `stripe listen --forward-to yourvirtualhost.localhost/endpoint`
3. trigger a stripe event like `stripe trigger payment_intent.created` or anything

### Traceback
`[ERROR] Failed to POST: Post "http://app.localhost/api/v1/webhooks/payments/subscriptions/charge": dial tcp: lookup api.teachizy.localhost: no such host`

I also tried with `app.localhost:80`, nothing works.

### Environment
- Windows Pro: 10.0.19
- Stripe CLI : 1.7.6
- Server: Apache/PHP

**Comment by pepin-stripe** [comment]
This doesn't seem to be an issue with the Stripe CLI - when passing a `forward-to` url to `stripe listen`, the CLI will use Go's `http.Client` to make a Post request to that url.

This error is coming directly from the `http.Client` mentioned so my guess is that if you `curl app.localhost/api/v1/webhooks/payments/subscriptions/charge` you'll have the same issue.

This is likely an issue with how the virtualhost is setup and how its host is (not) being resolved. I'd recommend looking into how to update your local `hosts` file to make sure the `app.localhost` is properly mapped.

Since this is not a Stripe CLI bug, I'll close this issue. Feel free to reopen if I'm mistaken and if you need more help.
