### ISSUE TITLE
chmod config.toml: operation not permitted 

### ISSUE THREAD

**Issue by lauterry** [stripe/stripe-cli#787]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue
I try to run `stripe login` then I got the following error : `FATA[0000] chmod /Users/lauthierry/.config/stripe/config.toml: operation not permitted `. However, when i run `sudo stripe login`, there is no error. Everything is ok.

### Expected Behavior
I expect the `stripe login` command to run properly without error

### Steps to reproduce
I installed stripe with `brew install stripe/stripe-cli/stripe`

### Traceback
`FATA[0000] chmod /Users/lauthierry/.config/stripe/config.toml: operation not permitted `

### Environment
macOS Big Sur 11.6

**Comment by pepin-stripe** [comment]
Hi @lauterry, 

The Stripe CLI does not require sudo access for anything - it does create the `/.config` folder if it doesn't exist, but when it does so, it doesn't require sudo.

Likely what happened is that the `/.config` folder was already created with sudo access before you installed the CLI. If you `ls` the folder, can you see other files/folder apart from stripe?

**Comment by pepin-stripe** [comment]
And to follow up, since this isn't a bug with the Stripe CLI so I am closing the ticket, but to unblock you here are a few steps:
1. you can try to `sudo rm -rf $HOME/.config/stripe` and try re-running / re-installing the stripe cli without sudo
2. use `chmod` to change the access rules to the `$HOME/.config/stripe` folder so it doesn't require root access

If you need further help reach out to support.stripe.com or the Discord https://discord.com/invite/stripe.
