### ISSUE TITLE
Listen stops silently after computer goes to sleep

### ISSUE THREAD

**Issue by renchap** [stripe/stripe-cli#80]
### Issue
I am using `stripe listen --forward-to` (amazing feature 🙇) on my mac. It is running in the foreground in one terminal tab.
When I leave my computer for some time (goes to sleep) and I come back, the command is still running but no new webhooks are received and forwarded

### Expected Behavior
I would expect the CLI to either quit when not connected, or (better) reconnect automatically

### Steps to reproduce
Run `stripe listen --forward-to`, but the computer to sleep for a while, come back, trigger a webhook and see it delivered

### Environment
macOS, installed using brew

**Comment by tomer-stripe** [comment]
Thanks @renchap! We'll look into this.

**Comment by rsl** [comment]
is there a way with the stripe rubygem to detect if `stripe listen` is really listening? over the past few months of developing for a stripe feature, i've had several times `stripe listen` seems to be running but after trying a checkout, i get caught in a loop because we're never getting webhooks then lo and behold https://dashboard.stripe.com/test/webhooks reveals stripe isn't seeing my computer for some new random reason. restarting cli fixes 100% of the time but it's really painful to hit this and have to reset my database records, delete the customer record on stripe, etc, etc.

**Comment by Anaphase** [comment]
Holy crap! After days of beating my head against a wall, it turns out this was my issue as well. `stripe listen` just stops working after my computer is awaken from sleep, even though the Stripe dashboard says my CLI is connected.

**Comment by richardm-stripe** [comment]
A fix for this went out in 1.4.3 (#468).

**Comment by jeromeetienne** [comment]
I still have the issue ```stripe --listen``` no more work after the computer went to sleep. and im running 1.5.5 on macosx. Any hint ?

im using ```stripe listen --forward-to example.orgr/my/path```

--- 

```
$ stripe -v
stripe version 1.5.5
```
