### ISSUE TITLE
Unable to set the amount when triggering a payment_intent

### ISSUE THREAD

**Issue by phollyer** [stripe/stripe-cli#983]
### Issue
I'm trying to set the `amount` for a `payment_intent`, but it seems to fail silently and falls back to the default value of 2000.

### Expected Behavior
Set the `amount` to be used when triggering the `payment_intent`

### Steps to reproduce
`stripe trigger payment_intent.succeeded --add payment_intent:amount=35000`

### Environment
MacOS

**Comment by remi-stripe** [comment]
@phollyer You have to use `--override` as an [option](https://stripe.com/docs/cli/trigger#trigger-override) here because `amount` is already set in the underlying fixture associated with that Event trigger [here](https://github.com/stripe/stripe-cli/blob/master/pkg/fixtures/triggers/payment_intent.succeeded.json#L11). 

You need to do this instead:

```
stripe trigger payment_intent.succeeded --override payment_intent:amount=35000
```
